steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/zests-repo/backend:latest', '.']
images:
- 'asia-south1-docker.pkg.dev/$PROJECT_ID/zests-repo/backend:latest'
